# Generated by Django 2.1 on 2018-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedButtonId', models.CharField(max_length=20)),
                ('timeValue', models.CharField(max_length=20)),
                ('tolerance', models.CharField(max_length=20)),
                ('timeStamp', models.CharField(max_length=20)),
            ],
        ),
    ]
